name: Scrape

on:
  push:
  schedule:
    - cron: '15 8 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install xmllint
      run: sudo apt-get install -y libxml2-utils

    - name: Fetch
      run: |-
        curl -sf --proto =https --tlsv1.3 https://www.gesetze-im-internet.de/gii-toc.xml | xmllint --format - > gii-toc.xml

    - name: Commit
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
